CERomerin/Controllers/ComprarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CERomerin.Controllers
{
    public class ComprarController : Controller
    {
        // GET: Comprar
        public ActionResult Paso1()
        {
            return View();
        }

        public ActionResult Paso2()
        {
            return View();
        }

        public ActionResult Paso3()
        {
            return View();
        }

        public ActionResult Paso4()
        {
            return View();
        }

        [HttpPost]
        public JsonResult RealizarPedido(List<Pedido> p)
        {

            return Json(true, JsonRequestBehavior.AllowGet);
        }

        public class Pedido
        {
            public int ProductoId { get; set; }
            public string Denominacion { get; set; }
            public int Cantidad { get; set; }
            public string Imagen { get; set; }
            public decimal Precio { get; set; }
        }
    }
}

CERomerin/Views/Comprar/Paso1.cshtml
@{
    Layout = null;
}


<!DOCTYPE html>
<!--[if lt IE 8]>      <html class="no-js lt-ie10 lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie10 lt-ie9"> <![endif]-->
<!--[if IE 9]>         <html class="no-js lt-ie10"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
 <!--<![endif]-->
<head>
    <meta charset="utf-8" />
    <title>Webmarket HTML Template - Checkout Step 1</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    <meta name="author" content="ProteusThemes" />
    <!--  Google Fonts  -->
    <link href='http://fonts.googleapis.com/css?family=Pacifico|Open+Sans:400,700,400italic,700italic&amp;subset=latin,latin-ext,greek' rel='stylesheet' type='text/css' />

    <!-- Twitter Bootstrap -->
    <link href="~/Resources/css/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Resources/css/css/responsive.css" rel="stylesheet" />
    <!-- Slider Revolution -->
    <link rel="stylesheet" href="~/Resources/js/rs-plugin/css/settings.css" type="text/css" />
    <!-- jQuery UI -->
    <link rel="stylesheet" href="~/Resources/js/jquery-ui-1.10.3/css/smoothness/jquery-ui-1.10.3.custom.min.css" type="text/css" />
    <!-- PrettyPhoto -->
    <link rel="stylesheet" href="~/Resources/js/prettyphoto/css/prettyPhoto.css" type="text/css" />
    <!-- main styles -->

    <link href="~/Resources/css/main.css" rel="stylesheet" />


    <!-- Modernizr -->
    <script src="~/Resources/js/modernizr.custom.56918.js"></script>


    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

</head>

<body class="checkout-page">





    <div class="container">
        <div class="row">

            <!--  ==========  -->
            <!--  = Main content =  -->
            <!--  ==========  -->
            <section class="span12">

                <div class="checkout-container">
                    <div class="row">
                        <div class="span10 offset1">

                            <!--  ==========  -->
                            <!--  = Header =  -->
                            <!--  ==========  -->
                            <header>
                                <div class="row">
                                    <div class="span2">
                                        <a href="index.html"><img src="~/Resources/images/logo-bw.png" alt="Webmarket Logo" width="48" height="48" /></a>
                                    </div>
                                    <div class="span6">
                                        <div class="center-align">
                                            <h1><span class="light">Review</span> Shopping Cart</h1>
                                        </div>
                                    </div>
                                    <div class="span2">
                                        <div class="right-align">
                                            <img src="~/Resources/images/buttons/security.jpg" alt="Security Sign" width="92" height="65" />
                                        </div>
                                    </div>
                                </div>
                            </header>

                            <!--  ==========  -->
                            <!--  = Steps =  -->
                            <!--  ==========  -->
                            <div class="checkout-steps">
                                <div class="clearfix">
                                    <div class="step active">
                                        <div class="step-badge">1</div>
                                        Shopping Cart
                                    </div>
                                    <div class="step">
                                        <div class="step-badge">3</div>
                                        Shipping Address
                                    </div>
                                    <div class="step">
                                        <div class="step-badge">2</div>
                                        Payment Method
                                    </div>
                                    <div class="step">
                                        <div class="step-badge">4</div>
                                        Confirm &amp; Pay
                                    </div>
                                </div>
                            </div> <!-- /steps -->
                            <!--  ==========  -->
                            <!--  = Selected Items =  -->
                            <!--  ==========  -->
                            <table class="table table-items">
                                <thead>
                                    <tr>
                                        <th colspan="2">Item</th>
                                        <th><div class="align-center">Quantity</div></th>
                                        <th><div class="align-right">Price</div></th>
                                    </tr>
                                </thead>
                                <tbody id="itemcarrito"></tbody>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td class="stronger">Total:</td>
                                    <td class="stronger"><div id="totalCompra" class="size-16 align-right">0.00</div></td>
                                </tr>
                            </table>
                            <hr />

                            <p class="right-align">
                                In the next step you will choose your shipping address &nbsp; &nbsp;
                                <a href='@Url.Action("Paso2","Comprar")' class="btn btn-primary higher bold">Continuar</a>
                            </p>

                        </div>
                    </div>
                </div>


            </section> <!-- /main content -->

        </div>
    </div> <!-- /container -->
    <!--  ==========  -->
    <!--  = JavaScript =  -->
    <!--  ==========  -->
    <!--  = FB =  -->

    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=126780447403102";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>


    <!--  = jQuery - CDN with local fallback =  -->
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript">
    if (typeof jQuery == 'undefined') {
        document.write('<script src="~/Resources/js/jquery.min.js"><\/script>');
    }
    </script>

    <!--  = _ =  -->
    <script src="~/Resources/js/underscore/underscore-min.js" type="text/javascript"></script>

    <!--  = Bootstrap =  -->
    <script src="~/Resources/js/bootstrap.min.js" type="text/javascript"></script>

    <!--  = Slider Revolution =  -->
    <script src="~/Resources/js/rs-plugin/pluginsources/jquery.themepunch.plugins.min.js" type="text/javascript"></script>
    <script src="~/Resources/js/rs-plugin/js/jquery.themepunch.revolution.min.js" type="text/javascript"></script>

    <!--  = CarouFredSel =  -->
    <script src="~/Resources/js/jquery.carouFredSel-6.2.1-packed.js" type="text/javascript"></script>

    <!--  = jQuery UI =  -->
    <script src="~/Resources/js/jquery-ui-1.10.3/js/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
    <script src="~/Resources/js/jquery-ui-1.10.3/touch-fix.min.js" type="text/javascript"></script>

    <!--  = Isotope =  -->
    <script src="~/Resources/js/isotope/jquery.isotope.min.js" type="text/javascript"></script>

    <!--  = Tour =  -->
    <script src="~/Resources/js/bootstrap-tour/build/js/bootstrap-tour.min.js" type="text/javascript"></script>

    <!--  = PrettyPhoto =  -->
    <script src="~/Resources/js/prettyphoto/js/jquery.prettyPhoto.js" type="text/javascript"></script>

   
    <!--  = Custom JS =  -->
    <script src="~/Resources/js/custom.js" type="text/javascript"></script>



    <script>
        $(function () {
            var carrito = localStorage.getItem("carrito");
            var productos = [];
            if (carrito != null) {
                productos = JSON.parse(carrito);
                CargarProductos(productos);
            }
        });
        function CargarProductos(productos) {
            var html = '';
            var total = 0;

            $.each(productos, function () {
                total += this.Precio * this.Cantidad
                html += '<tr>' +
                '            <td class="image"><img src="/ImgProductos/' + this.Imagen + '" alt="" width="124" height="124" /></td>' +
                '            <td class="desc">' + this.Denominacion + ' &nbsp; <a title="Remove Item" class="icon-remove-sign" href="#"></a></td>' +
                '            <td class="qty">' +
                '                <input type="text" class="tiny-size" value="' + this.Cantidad + '" />' +
                '           </td>' +
                '           <td class="price">S/. ' + this.Precio + '</td>' +
                '          </tr>'
            });
            $('#itemcarrito').html(html);

            $("#totalCompra").text('S/.' + total);
        }
    </script>

</body>
</html>

CERomerin/Views/Comprar/Paso3.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<!--[if lt IE 8]>      <html class="no-js lt-ie10 lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie10 lt-ie9"> <![endif]-->
<!--[if IE 9]>         <html class="no-js lt-ie10"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
 <!--<![endif]-->
<head>
    <meta charset="utf-8" />
    <title>Webmarket HTML Template - Checkout Step 1</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    <meta name="author" content="ProteusThemes" />


    <!-- Twitter Bootstrap -->
    <link href="~/Resources/css/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Resources/css/css/responsive.css" rel="stylesheet" />
    <!-- Slider Revolution -->
    <link rel="stylesheet" href="~/Resources/js/rs-plugin/css/settings.css" type="text/css" />
    <!-- jQuery UI -->
    <link rel="stylesheet" href="~/Resources/js/jquery-ui-1.10.3/css/smoothness/jquery-ui-1.10.3.custom.min.css" type="text/css" />
    <!-- PrettyPhoto -->
    <link rel="stylesheet" href="~/Resources/js/prettyphoto/css/prettyPhoto.css" type="text/css" />
    <!-- main styles -->

    <link href="~/Resources/css/main.css" rel="stylesheet" />


    <!-- Modernizr -->
    <script src="~/Resources/js/modernizr.custom.56918.js"></script>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>

<body class="checkout-page">





    <div class="container">
        <div class="row">

            <!--  ==========  -->
            <!--  = Main content =  -->
            <!--  ==========  -->
            <section class="span12">

                <div class="checkout-container">
                    <div class="row">
                        <div class="span10 offset1">

                            <!--  ==========  -->
                            <!--  = Header =  -->
                            <!--  ==========  -->
                            <header>
                                <div class="row">
                                    <div class="span2">
                                        <a href="index.html"><img src="~/Resources/images/logo-bw.png" alt="Webmarket Logo" width="48" height="48" /></a>
                                    </div>
                                    <div class="span6">
                                        <div class="center-align">
                                            <h1><span class="light">Choose</span> Payment Method</h1>
                                        </div>
                                    </div>
                                    <div class="span2">
                                        <div class="right-align">
                                            <img src="~/Resources/images/buttons/security.jpg" alt="Security Sign" width="92" height="65" />
                                        </div>
                                    </div>
                                </div>
                            </header>

                            <!--  ==========  -->
                            <!--  = Steps =  -->
                            <!--  ==========  -->
                            <div class="checkout-steps">
                                <div class="clearfix">
                                    <div class="step done">
                                        <div class="step-badge"><i class="icon-ok"></i></div>
                                        <a href="checkout-step-1.html">Shopping Cart</a>
                                    </div>
                                    <div class="step done">
                                        <div class="step-badge"><i class="icon-ok"></i></div>
                                        <a href="checkout-step-2.html">Shipping Address</a>
                                    </div>
                                    <div class="step active">
                                        <div class="step-badge">2</div>
                                        Payment Method
                                    </div>
                                    <div class="step">
                                        <div class="step-badge">4</div>
                                        Confirm &amp; Pay
                                    </div>
                                </div>
                            </div> <!-- /steps -->
                            <!--  ==========  -->
                            <!--  = Payment =  -->
                            <!--  ==========  -->
                            <span class="btn btn-danger circle pull-left"><i class="icon-chevron-down"></i></span>
                            <div class="shifted-left-45 clearfix">
                                <h3 class="no-margin"><span class="light">Credit</span> Card</h3>
                                <p class="push-down-30">We accept MasterCard, Visa and American Express</p>

                                <form action="#" method="post" class="form-horizontal form-checkout" />
                                <div class="control-group">
                                    <label class="control-label" for="firstName">First Name<span class="red-clr bold">*</span></label>
                                    <div class="controls">
                                        <input type="text" id="firstName" class="span4" required="" />
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="lastName">Last Name<span class="red-clr bold">*</span></label>
                                    <div class="controls">
                                        <input type="text" id="lastName" class="span4" required="" />
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="cardNum">Card Number<span class="red-clr bold">*</span></label>
                                    <div class="controls">
                                        <input type="text" id="cardNum" class="span1 card-num-input center-align" maxlength="4" />
                                        <input type="text" class="span1 card-num-input center-align" maxlength="4" />
                                        <input type="text" class="span1 card-num-input center-align" maxlength="4" />
                                        <input type="text" class="span1 card-num-input center-align add-tooltip" maxlength="4" data-title="The 16 digits on the front of the card" />
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="cvc">CVC or CVS<span class="red-clr bold">*</span></label>
                                    <div class="controls">
                                        <input id="cvc" type="text" class="span1 center-align add-tooltip" maxlength="3" data-title="Last 3 digits on back of card" required="" />
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="exp">Expiration Date<span class="red-clr bold">*</span></label>
                                    <div class="controls">
                                        <select id="exp" class="input-small month-push-right">
                                            <option value="-1" />Month
                                            <option value="1" />01
                                            <option value="2" />02
                                            <option value="3" />03
                                            <option value="4" />04
                                            <option value="5" />05
                                            <option value="6" />06
                                            <option value="7" />07
                                            <option value="8" />08
                                            <option value="9" />09
                                            <option value="10" />10
                                            <option value="11" />11
                                            <option value="12" />12

                                        </select>
                                        <select id="exp" class="input-small">
                                            <option value="-1" />Year
                                            <option value="2013" />2013
                                            <option value="2014" />2014
                                            <option value="2015" />2015
                                            <option value="2016" />2016
                                            <option value="2017" />2017
                                            <option value="2018" />2018
                                            <option value="2019" />2019

                                        </select>
                                    </div>
                                </div>
                                </form>
                            </div>

                            <hr />

                            <span class="btn btn-danger circle pull-left"><i class="icon-chevron-right"></i></span>
                            <div class="shifted-left-45 clearfix">
                                <h3 class="no-margin">
                                    <span class="light">PayPal</span> &nbsp; &nbsp; &nbsp;
                                    <a href="#"><img src="~/Resources/images/buttons/paypal.gif" alt="PayPal" width="145" height="42" /></a>
                                </h3>
                            </div>

                            <hr />

                            <p class="right-align">
                                In the next step you will be able to review and confirm the order &nbsp; &nbsp;
                                <a href='@Url.Action("Paso4","Comprar")' class="btn btn-primary higher bold">CONTINUE</a>
                            </p>


                        </div>
                    </div>
                </div>


            </section> <!-- /main content -->

        </div>
    </div> <!-- /container -->
    <!--  ==========  -->
    <!--  = JavaScript =  -->
    <!--  ==========  -->
    <!--  = FB =  -->

    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=126780447403102";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>


    <!--  = jQuery - CDN with local fallback =  -->
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript">
    if (typeof jQuery == 'undefined') {
        document.write('<script src="~/Resources/js/jquery.min.js"><\/script>');
    }
    </script>

    <!--  = _ =  -->
    <script src="~/Resources/js/underscore/underscore-min.js" type="text/javascript"></script>

    <!--  = Bootstrap =  -->
    <script src="~/Resources/js/bootstrap.min.js" type="text/javascript"></script>

    <!--  = Slider Revolution =  -->
    <script src="~/Resources/js/rs-plugin/pluginsources/jquery.themepunch.plugins.min.js" type="text/javascript"></script>
    <script src="~/Resources/js/rs-plugin/js/jquery.themepunch.revolution.min.js" type="text/javascript"></script>

    <!--  = CarouFredSel =  -->
    <script src="~/Resources/js/jquery.carouFredSel-6.2.1-packed.js" type="text/javascript"></script>

    <!--  = jQuery UI =  -->
    <script src="~/Resources/js/jquery-ui-1.10.3/js/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
    <script src="~/Resources/js/jquery-ui-1.10.3/touch-fix.min.js" type="text/javascript"></script>

 

    <!--  = Tour =  -->
    <script src="~/Resources/js/bootstrap-tour/build/js/bootstrap-tour.min.js" type="text/javascript"></script>

    <!--  = PrettyPhoto =  -->
    <script src="~/Resources/js/prettyphoto/js/jquery.prettyPhoto.js" type="text/javascript"></script>




    <!--  = Custom JS =  -->
    <script src="~/Resources/js/custom.js" type="text/javascript"></script>
</body>
</html>